node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/Raghav2211/sample-spring-microservices.git', credentialsId: 'test', branch: 'test'
            
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            echo "Create image"
        }

    }

}